In [21]:
import matplotlib
%matplotlib inline
import numpy as np
import pandas as pd
%load_ext autoreload
%autoreload 2

In [22]:
tracks_df = pd.read_csv("data/spotify_2017.csv")

tracks_df

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,7qiZfU4dY1lWllzX7mPBI,Shape of You,Ed Sheeran,0.825,0.652,1.0,-3.183,0.0,0.0802,0.5810,0.000000,0.0931,0.9310,95.977,233713.0,4.0
1,5CtI0qwDJkDQGwXD1H1cL,Despacito - Remix,Luis Fonsi,0.694,0.815,2.0,-4.328,1.0,0.1200,0.2290,0.000000,0.0924,0.8130,88.931,228827.0,4.0
2,4aWmUDTfIPGksMNLV2rQP,Despacito (Featuring Daddy Yankee),Luis Fonsi,0.660,0.786,2.0,-4.757,1.0,0.1700,0.2090,0.000000,0.1120,0.8460,177.833,228200.0,4.0
3,6RUKPb4LETWmmr3iAEQkt,Something Just Like This,The Chainsmokers,0.617,0.635,11.0,-6.769,0.0,0.0317,0.0498,0.000014,0.1640,0.4460,103.019,247160.0,4.0
4,3DXncPQOG4VBw3QHh3S81,I'm the One,DJ Khaled,0.609,0.668,7.0,-4.284,1.0,0.0367,0.0552,0.000000,0.1670,0.8110,80.924,288600.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1PSBzsahR2AKwLJgx8ehB,Bad Things (with Camila Cabello),Machine Gun Kelly,0.675,0.690,2.0,-4.761,1.0,0.1320,0.2100,0.000000,0.2870,0.2720,137.817,239293.0,4.0
96,0QsvXIfqM0zZoerQfsI9l,Don't Let Me Down,The Chainsmokers,0.542,0.859,11.0,-5.651,1.0,0.1970,0.1600,0.004660,0.1370,0.4030,159.797,208053.0,4.0
97,7mldq42yDuxiUNn08nvzH,Body Like A Back Road,Sam Hunt,0.731,0.469,5.0,-7.226,1.0,0.0326,0.4630,0.000001,0.1030,0.6310,98.963,165387.0,4.0
98,7i2DJ88J7jQ8K7zqFX2fW,Now Or Never,Halsey,0.658,0.588,6.0,-4.902,0.0,0.0367,0.1050,0.000001,0.1250,0.4340,110.075,214802.0,4.0
99,1j4kHkkpqZRBwE0A4CN4Y,Dusk Till Dawn - Radio Edit,ZAYN,0.258,0.437,11.0,-6.593,0.0,0.0390,0.1010,0.000001,0.1060,0.0967,180.043,239000.0,4.0

In [23]:
tracks_df[['artists', 'name']].head()

            artists                                name
0        Ed Sheeran                        Shape of You
1        Luis Fonsi                   Despacito - Remix
2        Luis Fonsi  Despacito (Featuring Daddy Yankee)
3  The Chainsmokers            Something Just Like This
4         DJ Khaled                         I'm the One

In [24]:
import requests

def fetch_lyrics(artists, title):
    """
    Get lyrics from Seeds Lyrics API. Returns empty string if song not found
    """
    url = f'https://lyrics.lewagon.ai/search?artist={artists}&title={title}'
    response = requests.get(url)
    if response.status_code != 200:
        return ''
    data = response.json()
    return data['lyrics']

In [25]:
fetch_lyrics('The Beatles', 'Come Together')

'Here come old flat-top, he come groovin\' up slowly\nHe got ju-ju eyeball, he one holy roller\nHe got hair down to his knee\nGot to be a joker, he just do what he please\n\nHe wear no shoeshine, he got toe-jam football\nHe got monkey finger, he shoot Coca-Cola\nHe say, "I know you, you know me"\nOne thing I can tell you is you got to be free\n\nCome together, right now\nOver me\n\nHe bag production, he got walrus gumboot\nHe got Ono sideboard, he one spinal cracker\nHe got feet down below his knee\nHold you in his armchair, you can feel his disease\n\nCome together, right now\nOver me\n\nRight!\n\nCome, come, come, come...\n\nHe roller-coaster, he got early warnin\'\nHe got muddy water, he one mojo filter\nHe say, "One and one and one is three"\nGot to be good-lookin\' \'cause he\'s so hard to see\n\nCome together, right now\nOver me\n\nUgh!\n\nCome together, yeah\nCome together, yeah\nCome together, yeah\nCome together, yeah\nCome together, yeah\nCome together, yeah\nCome together, yeah\nAgh!\nCome together, yeah\nCome together, yeah\nCome together...'

In [26]:
fetch_lyrics('The Beatles', "Wouldn't it be nice")

''

In [29]:
from music import fetch_lyrics

In [30]:
fetch_lyrics("The Beatles", "Come not together")

"Here come old flat top\nHe come groovin' up slowly\nHe got ju-ju eyeball\nHe one holy roller\nHe got hair down to his knees\nGot to be a joker\nHe just do what he please\n\nHe wear no shoeshine\nHe got toe jam football\nHe got monkey finger\nHe shoot Coca Cola\nHe say I know you, you know me\nOne thing I can tell you is\nYou got to be free\nCome together, right now\nOver me\n\nHe bag production\nHe got walrus gumboot\nHe got Ono sideboard\nHe one spinal cracker\nHe got feet down below his knees\nHold you in his arms yeah\nYou can feel his disease\nCome together, right now\nOver me\n\nHe roller coaster\nHe got early warning\nHe got muddy water\nHe one Mojo filter\nHe say one and one and one is three\nGot to be good looking\n'Cause he's so hard to see\nCome together right now\nOver me\n\nCome together, yeah\nCome together, yeah\nCome together, yeah\nCome together, yeah\nCome together, yeah\nCome together, yeah\nCome together, yeah\nCome together, yeah\nCome together, yeah\nCome together, yeah"

In [31]:
fetch_lyrics('The Beatles', "Wouldn't it be nice")

'NO LYRICS'

In [32]:
tracks_df['Lyrics']= ""

In [33]:
tracks_df

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,Lyrics
0,7qiZfU4dY1lWllzX7mPBI,Shape of You,Ed Sheeran,0.825,0.652,1.0,-3.183,0.0,0.0802,0.5810,0.000000,0.0931,0.9310,95.977,233713.0,4.0,
1,5CtI0qwDJkDQGwXD1H1cL,Despacito - Remix,Luis Fonsi,0.694,0.815,2.0,-4.328,1.0,0.1200,0.2290,0.000000,0.0924,0.8130,88.931,228827.0,4.0,
2,4aWmUDTfIPGksMNLV2rQP,Despacito (Featuring Daddy Yankee),Luis Fonsi,0.660,0.786,2.0,-4.757,1.0,0.1700,0.2090,0.000000,0.1120,0.8460,177.833,228200.0,4.0,
3,6RUKPb4LETWmmr3iAEQkt,Something Just Like This,The Chainsmokers,0.617,0.635,11.0,-6.769,0.0,0.0317,0.0498,0.000014,0.1640,0.4460,103.019,247160.0,4.0,
4,3DXncPQOG4VBw3QHh3S81,I'm the One,DJ Khaled,0.609,0.668,7.0,-4.284,1.0,0.0367,0.0552,0.000000,0.1670,0.8110,80.924,288600.0,4.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1PSBzsahR2AKwLJgx8ehB,Bad Things (with Camila Cabello),Machine Gun Kelly,0.675,0.690,2.0,-4.761,1.0,0.1320,0.2100,0.000000,0.2870,0.2720,137.817,239293.0,4.0,
96,0QsvXIfqM0zZoerQfsI9l,Don't Let Me Down,The Chainsmokers,0.542,0.859,11.0,-5.651,1.0,0.1970,0.1600,0.004660,0.1370,0.4030,159.797,208053.0,4.0,
97,7mldq42yDuxiUNn08nvzH,Body Like A Back Road,Sam Hunt,0.731,0.469,5.0,-7.226,1.0,0.0326,0.4630,0.000001,0.1030,0.6310,98.963,165387.0,4.0,
98,7i2DJ88J7jQ8K7zqFX2fW,Now Or Never,Halsey,0.658,0.588,6.0,-4.902,0.0,0.0367,0.1050,0.000001,0.1250,0.4340,110.075,214802.0,4.0,
99,1j4kHkkpqZRBwE0A4CN4Y,Dusk Till Dawn - Radio Edit,ZAYN,0.258,0.437,11.0,-6.593,0.0,0.0390,0.1010,0.000001,0.1060,0.0967,180.043,239000.0,4.0,

In [34]:
%%time
for index, row in tracks_df.head(3).iterrows():
    print(f"Fetching lyrics for {row['artists']} - {row['name']}")
    lyrics = fetch_lyrics(row['artists'], row['name'])
    tracks_df.loc[index, 'lyrics'] = lyrics

Fetching lyrics for Ed Sheeran - Shape of You
Fetching lyrics for Luis Fonsi - Despacito - Remix
Fetching lyrics for Luis Fonsi - Despacito (Featuring Daddy Yankee)
CPU times: user 132 ms, sys: 0 ns, total: 132 ms
Wall time: 1.95 s

In [37]:
print(tracks_df.loc[1, 'lyrics'][0:150])

NO LYRICS

In [39]:
tracks_df.head(3)

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,Lyrics,lyrics
0,7qiZfU4dY1lWllzX7mPBI,Shape of You,Ed Sheeran,0.825,0.652,1.0,-3.183,0.0,0.0802,0.581,0.0,0.0931,0.931,95.977,233713.0,4.0,,The club isn't the best place to find a lover\...
1,5CtI0qwDJkDQGwXD1H1cL,Despacito - Remix,Luis Fonsi,0.694,0.815,2.0,-4.328,1.0,0.1200,0.229,0.0,0.0924,0.813,88.931,228827.0,4.0,,NO LYRICS
2,4aWmUDTfIPGksMNLV2rQP,Despacito (Featuring Daddy Yankee),Luis Fonsi,0.660,0.786,2.0,-4.757,1.0,0.1700,0.209,0.0,0.1120,0.846,177.833,228200.0,4.0,,NO LYRICS

In [43]:
import pandas as pd
import sqlite3
conn = sqlite3.connect("data/soccer.sqlite")

In [44]:
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
print(cursor.fetchall())

[]

In [45]:
league_df = pd.read_sql(
    '''
    SELECT l.id, l.name, c.name as country_name
    FROM League l
    JOIN Country c ON c.id = l.country_id
    ''', conn)

DatabaseError: Execution failed on sql '
    SELECT l.id, l.name, c.name as country_name
    FROM League l
    JOIN Country c ON c.id = l.country_id
    ': no such table: League

In [46]:
league_df.head(3)

NameError: name 'league_df' is not defined

In [68]:
import re
import requests
from bs4 import BeautifulSoup

In [86]:
response = requests.get("https://www.imdb.com/list/ls055386972/", headers={"Accept-Language":"en-US"})
soup = BeautifulSoup(response.content, "html.parser")

In [70]:
movies = []
for movie in soup.find_all("div", class_="lister-item-content"):
    title = movie.find("h3").find("a").string
    duration = int(movie.find(class_="runtime").string.strip(' min'))
    year = int(re.search(r"\d{4}", movie.find(class_="lister-item-year").string).group(0))
    movies.append({'title': title, 'duration': duration, 'year': year})
print(movies[0])

{'title': 'The Godfather', 'duration': 175, 'year': 1972}

In [71]:
movies_df = pd.DataFrame(movies)
movies_df.head()

                            title  duration  year
0                   The Godfather       175  1972
1                Schindler's List       195  1993
2                    12 Angry Men        96  1957
3               Life Is Beautiful       116  1997
4  The Good, the Bad and the Ugly       178  1966

In [72]:
movies_dict = {'title': [], 'duration': [], 'year': []}
for movie in soup.find_all("div", class_="lister-item-content"):
    movies_dict['title'].append(movie.find("h3").find("a").string)
    movies_dict['duration'].append(int(movie.find(class_="runtime").string.strip(' min')))
    movies_dict['year'].append(int(re.search(r"\d{4}", movie.find(class_="lister-item-year").string).group(0)))
print(movies_dict['title'][0:2])

['The Godfather', "Schindler's List"]

In [73]:
movies_dict_df = pd.DataFrame.from_dict(movies_dict)
movies_dict_df.head()

                            title  duration  year
0                   The Godfather       175  1972
1                Schindler's List       195  1993
2                    12 Angry Men        96  1957
3               Life Is Beautiful       116  1997
4  The Good, the Bad and the Ugly       178  1966

In [104]:
def fetch_page(page):
    response = requests.get(
        "https://www.imdb.com/search/title/",
        params={"groups":"top_250", "sort":"user_rating","start": (1 + page * 50)},
        headers={"Accept-Language":"en-US"})
    soup = BeautifulSoup(response.content, "html.parser")
    return soup

In [105]:
def parse_movies(soup):
    movies = []
    for movie in soup.find_all("div", class_="lister-item-content"):
        title = movie.find("h3").find("a").string
        duration = int(movie.find(class_="runtime").string.strip(' min'))
        year = int(re.search(r"\d{4}", movie.find(class_="lister-item-year").string).group(0))
        movies.append({'title': title, 'duration': duration, 'year': year})
    return movies

In [106]:
all_movies = []
for page in range(5):
    print(f"Parsing page {page + 1}...")
    soup = fetch_page(page)
    print(soup)
    all_movies += parse_movies(soup)
    print(all_movies)
      
# print("Done")

Parsing page 1...
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

[]
Parsing page 2...
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

[]
Parsing page 3...
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

[]
Parsing page 4...
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

[]
Parsing page 5...
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

[]

In [82]:
all_movies_df = pd.DataFrame(all_movies)

all_movies_df.head()

Empty DataFrame
Columns: []
Index: []

In [83]:
all_movies_df.hist(grid=False, bins=12, figsize=(12, 4))

ValueError: hist method requires numerical or datetime columns, nothing to plot.

In [114]:
!curl 'https://opengraph.lewagon.com/?url='

{"error":"Please provide a URL to scrape","example_url":"https://opengraph.lewagon.com/?url=https://www.lewagon.com"}

In [113]:
!curl 'https://opengraph.lewagon.com/?url=https://www.facebook.com'

{"error":"Missing required attribute: title","url":"https://www.facebook.com"}